version: "3.9"
services:
  nginx_container:
    container_name: nginx_container_2
    image: nginx
    ports:
      - "82:80"
    networks:
      - my_network 
  httpd:
    container_name: httpd_container
    image: httpd
    ports:
      - "81:80"
    networks:
      - my_network
  
networks:
  my_network:
    driver: bridge
    external: true
